### PR TITLE
add multi_touch event

### PR DESCRIPTION
**Pull request by Didifred**
multi_touch allows the application to handle additionnal fingers touches.
The first touch will be considerated as single_touch release (pressed=false).
This strategy allows to not loose a release event in case of multiples touches.
If accepted, i can modify readme as well.

### CODE REVIEW

**Comment by Federico-Ciuffardi** [comment]
Hi, thanks for using and contributing to this project!

I think multiple touches can be handled natively with [InputEventScreenTouch](https://docs.godotengine.org/en/stable/classes/class_inputeventscreentouch.html). This allows one or more touches to be handled, without losing launch events, and even assigning an identification to each touch.

The `InputEventSingleScreenTouch` event should be used when multiple touches invalidate an interaction (I don't know if this is really useful).

If there's something you want to do with multiple touches and it can't be done with `InputEventScreenTouch`, let me know and we'll see how to add it.

**Comment by Didifred** [comment]
Hi, it is a pleasure to contribute for this class that is usefull for me.
On actual master branch, i have the problem that when the user does another touch after an single touch (still pressed), i will never have the release event of that single touch. And in another case, i want  to invalidate the single touch in progress if by accident user does mutli touch.
I've got your point about using native InputEventScreenTouch, but i think that still InputManager shall handle a signal multi_touch, so instead of instantiating a custum event in my proposal 'emit("multi_touch", InputEventMultiScreenTouch.new(event))' , we shall do simply emit("multi_touch", event) using native InputEventScreenTouch.

Let's me know if it sounds better for you ;).

**Comment by Federico-Ciuffardi** [comment]
I still think that the problems you propose can be handled with the current implementation and `InputEventScreenTouch`.

> i have the problem that when the user does another touch after an single touch (still pressed), i will never have the release event of that single touch.

If you want that behavior, you can use `InputEventScreenTouch` and check for` index = 0` instead of `InputEventSingleScreenTouch`. 

> And in another case, i want to invalidate the single touch in progress if by accident user does mutli touch.

The invalidation of the single touch means that it won't have a release event. Here you should use `InputEventSingleScreenTouch`.

**Comment by Didifred** [comment]
Of course i can solve these problems outside "Touch-Input-Manager" since itself is based on native touch events of Godot Engine.
But to do that will result in a messy design, obviously user would like to use "Touch-Input-Manager" without taking care of native events.
After the user touch the screen with a second finger, the event `InputEventSingleScreenTouch, pressed=false` for the first finger release will be never fired. I consider it is a bug of "Touch-Input-Manager".

>And in another case, i want to invalidate the single touch in progress if by accident user does mutli touch.
>>The invalidation of the single touch means that it won't have a release event. Here you should use InputEventSingleScreenTouch.

No, in this case after the `InputEventSingleScreenTouch, pressed=true`, i want to have the event of the second finger pressed (multi_touch signal) to invalidate my current applicative action of the single touch in progress. In what you propose, again i have no information about several touches unless i implement in parallel native handling events ...

**Comment by Federico-Ciuffardi** [comment]
Maybe you are using signals instead of something like [_input(InputEventevent)](https://docs.godotengine.org/en/3.1/classes/class_node.html#class-node-method-input), so you want to be able to get the input events as signals. 

If this is the case forwarding the `InputEventScreenTouch` to a signal without parsing it with  [parse_input_event](https://docs.godotengine.org/en/stable/classes/class_input.html#class-input-method-parse-input-event) as you mentioned before, makes sense.

Otherwise, what I meant is that doing what you propose just adds redundant information that can easily be obtained natively. In other words, the `InputEventMultiScreenTouch` event that you propose is practically the same as `InputEventScreenTouch`. For example using  [_unhandled_input(InputEventevent)](https://docs.godotengine.org/en/3.1/classes/class_node.html#class-node-method-unhandled-input):
```python
func _unhandled_input(e):
  if e is InputEventSingleScreenTouch:
    # Code for the current InputEventSingleScreenTouch
  elif e is InputEventScreenTouch:
    if e.index == 0:
      # Code for the InputEventSingleScreenTouch as you propose it
    if e.index != 0:
      # Code for the InputEventMultiScreenTouch as you propose it
```

> After the user touch the screen with a second finger, the event InputEventSingleScreenTouch, pressed=false for the first finger release will be never fired. I consider it is a bug of "Touch-Input-Manager".

And this, as I said above, is a feature and not a bug (seriously). It can be used if you just want the release to confirm something that must only happen if the user did not use another finger in the process. As I also said, maybe this is not that useful, and in that case I would say this event should be removed and to just use `InputEventScreenTouch`.

**Comment by Didifred** [comment]
> Maybe you are using signals instead of something like _input(InputEventevent), so you want to be able to get the input events as signals.

Yes, i use signals. This explains a part of our misalignment.

> And this, as I said above, is a feature and not a bug (seriously). 

Ok, sorry for the buzz word ;), the release event signaling is highest in importance for me.
To fullfill both features, maybe to add a bool propriety "cancelled= true, pressed=true" in `InputEventSingleScreenTouch `signal when a second finger touch the screen. The signal will be also send at release with "cancelled=true, pressed=false"
With that additionnal info, both features (mine and initial code) are covered.

I would not remove SingleTouch from Touch-Input-Manager, because in this case you can also remove SingleDrag that can be also done with native implementation (testing index=0) ..., no ?

> If this is the case forwarding the InputEventScreenTouch to a signal without parsing it with parse_input_event as you mentioned before makes sense.

If we implement, the propriety `cancelled `in `InputEventSingleScreenTouch `, i no more need events for mutli touch for my problems. But we can implement` emit("multi_touch", event)` in Touch-Input-Manager  using native `InputEventScreenTouch` for any other needs.

**Comment by Federico-Ciuffardi** [comment]
1. I think GDTIM (abbreviated project name) should not include events for multitouch as you propose. 

I would like GDTIM generated events to represent gestures, meaning that the events should consider all the finger touching the screen. To handle multiple individual touches and multiple individual drags, the native events should be used.

So the multitouch event I would like is one that has to involves all the fingers at once (like the multidrag), I'm not sure exaclty how, maybe there can be more than one event related to multiple touches (like twist and pan are related to multidrag).

2. I like the cancelled propriety. But...
  
For consistency a cancellation event for single finger drag would be needed. 

And also once there is another touch, the single touch must be canceled and no subsequent release event should occur, as this is inconsistent with the single drag that cannot continue once it is canceled. I mean, maybe we could have the subsequent release-cancelled event but there is that consistency issue.

**Comment by Didifred** [comment]
1- My PR is one solution to close the gap with the missing of information when an single push is cancelled by another finger : no release event and no cancellation event. I can understand that the solution do not fit your design concept but the problem shall be addressed ...

2- Just touch signal, you mean to just forward every InputEventScreenTouch event, this is total contradiction with the point 1 ...
You can see my proposal PR "multi_touch" signal as a filtered InputEventScreenTouch event, that is different than native events, "multi_touch" is the complement of "single_touch" that's why redefines InputEventMultiScreenTouch make sense. By the way, similarly you redefine "single_touch" and "single_drag" events based on raw events ...

3- I do not see any consistency issue about my second proposal. 

- After a single_touch (pressed=true) event due to the fact a fisrt finger touch the screen, when a second finger touch the screen, instead of no information at all in current implementation, an event single_touch (pressed=true, cancelled=true ) is send. When the first finger no more touch the screen, an event single_touch (pressed=false, cancelled=true ) is send instead of no information at all in current implementation.

> the single touch must be canceled and no subsequent release event should occur
This is the actual weakness of current implementation ! 
With the proposal, user code can dot something or nothing (like your wish).

- For "single_drag", cancellation is implicit with others drags > 1 like  pinch, multi_drag, twist.
   Note that with "muti_touch", cancellation is implicit too ...

**Comment by Federico-Ciuffardi** [comment]
> I can understand that the solution do not fit your design concept but the problem shall be addressed ...

I never said that the problem does not have to be addressed. Just wanted to state my design concept and why your first proposal does not fit. And also mention how I would like multitouch events to be.

>  Just touch signal, you mean to just forward every InputEventScreenTouch event, this is total contradiction with the point 1

No, like I said, it could be useful if someone wants to use signals. As `InputEventScreenTouch` are already available natively when using `_input` (for example), this would only make those events available to signal users. 

> By the way, similarly you redefine "single_touch" and "single_drag" events based on raw events ...

Those involve all the fingers on the screen, that is the difference. Please read again the point `1.` of my [previous comment](https://github.com/Federico-Ciuffardi/Godot-Touch-Input-Manager/pull/14#issuecomment-1000943329).

> For "single_drag", cancellation is implicit with others drags > 1 like pinch, multi_drag, twist.
Note that with "muti_touch", cancellation is implicit too ...

If you think that implicit cancellation is OK there are 2 options:
1.  Design and implement at least one type of multitouch event that considers all fingers at the same time. 

2. Remove `InputEventSingleScreenTouch` and just use the [code I proposed above](https://github.com/Federico-Ciuffardi/Godot-Touch-Input-Manager/pull/14#issuecomment-1000560878) as it enables the functionality of your fist implementation in a simpler way. 
   * By simple I mean without introducing new concepts and code to GDTIM, when an easy native equivalent is available. 
   * Please check the code as it seems you ignored it the first time. 
   * I would also appreciate if you could try this code and tell me if it works well in your use case. 

Otherwise there is another option:

  3. I think it's best to implement the `canceled` property on the `InputEventSingleScreenTouch` and make the single touch an exception with explicit cancellation. I think the exception is justified since this gesture is also the only one with an explicit release (`pressed = false`). 
     * Emitting a `InputEventSingleScreenTouch` with `(pressed=true, cancelled=true )` and `(pressed=false, cancelled=true)`  as you originally proposed.

### My thoughts
* Option `1.` is the best but the hardest.

* Option `2` is the easiest (no implementation required in GDTIM) and avoids bloat. This could be an alternative until option `1` is implemented.

* Option `3.` provides explicit cancellation which I think is useful. Maybe we could implement this first and then merge it with option `1.`.
    * I wonder if other events can benefit from having an explicit cancellation

**Comment by Didifred** [comment]
> I never said that the problem does not have to be addressed. Just wanted to state my design concept and why your first proposal does not fit. And also mention how I would like multitouch events to be.

Ok, perfect. I have now the gestures with all fingers (including only one) scope in mind.

> As InputEventScreenTouch are already available natively when using _input (for example), this would only make those events available to signal users.

Honestly, this feature is totally independant of GDTIM gestures, and can be done easily outside.

I'm agree with your thoughts. 
I will not try the option 2 as it is done outside GDTIM to patch cancellation weakeness of actual GDTIM code, i prefer to find a coherent solution integrated in GDTIM.
I do not need to recognize new gestures like 2 fingers press for option 1.
So it remains the option 3 that i can implement.

But i think about another way let's say the option 4 to solves the cancellation notificaition problem, more elegant, that can be extended to other gesture events if needs, no modification of actual single_touch event emit :
The idea is to create a signal "gesture_cancel" with an extendded `InputEventAction->InputEventGestureCancel` event with a `.name` property (exemple "single_touch") and a `.native_event` property with type `InputEventScreenTouch`.
Here the native touches are only forwarded for cancellation that make sense for that notification purpose.
So when a single touch is cancelled with a second finger pressed, the signal `gesture_cancel` is emitted with native touch event  and gesture name "single_touch". Then when the first finger is released, the signal `gesture_cancel` is emitted with native touch event  and gesture name "single_touch". User code can use or not these notifications depending on the needs. One can consider a "single_touch" (released) valid even if cancelled in between by a another finger touch.

Hope you find option 4 it good too ! 
I think it fullfills your design concepts and close the weakness of loosing released event of single_touch being not notified of the cancellation.

**Comment by Federico-Ciuffardi** [comment]
> Honestly, this feature is totally independant of GDTIM gestures, and can be done easily outside.

I agree, although I would add it if someone requests it. Otherwise, all GDTIM signals should be removed as these can also easily be done outside with almost identical code.  Perhaps the most useful thing would be send all the signals related to touch input and allow to enable/disable this feature as perhaps they have a non-negligible computational cost. Anyway this is not related to this PR.

Going back to the subject of this PR, I think option 3 is  better in that it is simpler both in terms of code and in terms of ease of use and understanding by users. 

Although I will consider option 4 if option 3 proves too simple for some tasks or if there is a need to cancel more gestures.

**Comment by Didifred** [comment]
Ok, so let's keep it simple with option 3. I will create another PR, implementing solution 3. 
Iinitial solution doesn't fit with design concept, i close this one.

**Pull request closed without merging**
